"""
Timeline Export.

Generates FCPXML, EDL, and other timeline formats for NLE import.
"""

import html
import math
from datetime import timedelta
from pathlib import Path
from typing import Optional
from xml.etree import ElementTree as ET

from grokfilmstudio.models.shotlist import Shot, Shotlist


class TimelineExport:
    """
    Exports timelines to various NLE formats.

    Supported formats:
    - FCPXML (Final Cut Pro X)
    - CMX3600 EDL (Universal)
    - Premiere Pro XML
    """

    def __init__(self, shotlist: Shotlist, project_name: str = "Project"):
        """
        Initialize timeline exporter.

        Args:
            shotlist: The project shotlist
            project_name: Project name for metadata
        """
        self.shotlist = shotlist
        self.project_name = project_name

    def to_fcpxml(self, output_path: Path) -> Path:
        """
        Export to FCPXML format.

        Args:
            output_path: Output file path

        Returns:
            Path to exported file
        """
        # FCPXML namespace
        ns = "{http://www.apple.com/finalcut/1.10}"

        # Root element
        fcpxml = ET.Element("fcpxml", version="1.10")

        # Resources section
        resources = ET.SubElement(fcpxml, "resources")

        # Format definition
        ET.SubElement(
            resources,
            "format",
            id="r1",
            name="FFVideoFormat1080p24",
            width="1920",
            height="1080",
            frameDuration="1/24s",
        )

        # Add assets for each shot with video
        resource_id = 2
        shot_resources = {}

        for shot in self.shotlist.shots:
            if shot.video_path:
                res_id = f"r{resource_id}"
                shot_resources[shot.shot_id] = res_id

                # Calculate duration
                duration = self._format_duration_fcpxml(shot.duration_seconds)

                ET.SubElement(
                    resources,
                    "asset",
                    id=res_id,
                    name=f"{shot.shot_id}",
                    src=self._path_to_file_url(shot.video_path),
                    duration=duration,
                    hasVideo="1",
                    hasAudio="1" if shot.audio_path else "0",
                )
                resource_id += 1

        # Sequence section
        sequence = ET.SubElement(fcpxml, "sequence")
        spine = ET.SubElement(sequence, "spine")

        # Add clips in order
        current_time = timedelta()

        for shot in self.shotlist.shots:
            if shot.shot_id not in shot_resources:
                continue

            duration_td = timedelta(seconds=shot.duration_seconds)
            duration_str = self._format_duration_fcpxml(shot.duration_seconds)
            offset_str = self._format_duration_fcpxml(current_time.total_seconds())

            clip = ET.SubElement(
                spine,
                "asset-clip",
                ref=shot_resources[shot.shot_id],
                offset=offset_str,
                duration=duration_str,
                name=shot.shot_id,
            )

            # Add metadata
            metadata = ET.SubElement(clip, "metadata")
            ET.SubElement(
                metadata, "key", key="finalcut:Note", value=shot.action_description
            )

            current_time += duration_td

        # Write XML
        tree = ET.ElementTree(fcpxml)
        ET.indent(tree, space="  ")
        tree.write(output_path, encoding="UTF-8", xml_declaration=True)

        return output_path

    def to_edl(self, output_path: Path, fps: float = 24.0) -> Path:
        """
        Export to CMX3600 EDL format.

        Args:
            output_path: Output file path
            fps: Frames per second for timecode

        Returns:
            Path to exported file
        """
        lines = []

        # Title
        lines.append(f"; {self.project_name}")
        lines.append(f"; Generated by GrokFilmStudio")
        lines.append("")

        # Process each shot
        event_num = 1
        record_time = timedelta()

        for shot in self.shotlist.shots:
            if not shot.video_path:
                continue

            # Source timecode (start from 0)
            source_in = timedelta()
            source_out = timedelta(seconds=shot.duration_seconds)

            # Record timecode (cumulative)
            record_in = record_time
            record_out = record_time + timedelta(seconds=shot.duration_seconds)

            # Format timecodes
            source_in_tc = self._format_timecode_edl(source_in, fps)
            source_out_tc = self._format_timecode_edl(source_out, fps)
            record_in_tc = self._format_timecode_edl(record_in, fps)
            record_out_tc = self._format_timecode_edl(record_out, fps)

            # Reel name (use shot ID)
            reel = f"{shot.shot_id:<8}"[:8]

            # EDL line
            line = f"{event_num:03d}  {reel} V     C        {source_in_tc} {source_out_tc} {record_in_tc} {record_out_tc}"
            lines.append(line)

            # Comment with filename
            lines.append(f"* FROM CLIP: {Path(shot.video_path).name}")

            # Add audio note if present
            if shot.audio_script:
                lines.append(f"* AUDIO: {shot.audio_script[:50]}...")

            lines.append("")

            event_num += 1
            record_time = record_out

        # Write file
        with open(output_path, "w") as f:
            f.write("\n".join(lines))

        return output_path

    def to_premiere_xml(self, output_path: Path) -> Path:
        """
        Export to Premiere Pro XML format.

        Args:
            output_path: Output file path

        Returns:
            Path to exported file
        """
        # Premiere XML namespace
        ns = "{http://www.adobe.com/project"

        # Root element
        xmeml = ET.Element("xmeml", version="5")
        sequence = ET.SubElement(xmeml, "sequence", explodedTracks="true")
        ET.SubElement(sequence, "name").text = self.project_name

        # Duration in ticks (254016000000 = 24fps, 1 hour)
        total_duration = sum(s.duration_seconds for s in self.shotlist.shots if s.video_path)
        ET.SubElement(sequence, "duration").text = str(int(total_duration * 254016000000))

        # Rate
        rate = ET.SubElement(sequence, "rate")
        ET.SubElement(rate, "timebase").text = "24"
        ET.SubElement(rate, "ntsc").text = "FALSE"

        # Timecode
        tc = ET.SubElement(sequence, "timecode")
        ET.SubElement(tc, "rate").text = "24"
        ET.SubElement(tc, "frame").text = "0"
        ET.SubElement(tc, "displayformat").text = "NDF"

        # Tracks
        media = ET.SubElement(sequence, "media")

        # Video track
        video = ET.SubElement(media, "video")
        vtrack = ET.SubElement(video, "track")

        current_time = 0
        for shot in self.shotlist.shots:
            if not shot.video_path:
                continue

            clip = ET.SubElement(vtrack, "clipitem")
            ET.SubElement(clip, "name").text = shot.shot_id

            # File reference
            file_el = ET.SubElement(clip, "file")
            ET.SubElement(file_el, "name").text = Path(shot.video_path).name
            ET.SubElement(file_el, "pathurl").text = shot.video_path

            # Timing
            ET.SubElement(clip, "start").text = str(current_time)
            ET.SubElement(clip, "end").text = str(current_time + int(shot.duration_seconds * 254016000000))
            ET.SubElement(clip, "in").text = "0"
            ET.SubElement(clip, "out").text = str(int(shot.duration_seconds * 254016000000))

            current_time += int(shot.duration_seconds * 254016000000)

        # Audio track
        audio = ET.SubElement(media, "audio")
        ET.SubElement(audio, "format")
        ET.SubElement(audio, "track")

        # Write XML
        tree = ET.ElementTree(xmeml)
        ET.indent(tree, space="  ")
        tree.write(output_path, encoding="UTF-8", xml_declaration=True)

        return output_path

    def _format_duration_fcpxml(self, seconds: float) -> str:
        """Format duration for FCPXML (e.g., '0/1000s' or '5s')."""
        if seconds == int(seconds):
            return f"{int(seconds)}s"
        else:
            # Use fractional format
            frames = int(seconds * 24)  # 24fps
            return f"{frames}/24s"

    def _format_timecode_edl(self, td: timedelta, fps: float) -> str:
        """Format timecode for EDL (HH:MM:SS:FF)."""
        total_seconds = td.total_seconds()
        hours = int(total_seconds // 3600)
        minutes = int((total_seconds % 3600) // 60)
        seconds = int(total_seconds % 60)
        frames = int((total_seconds % 1) * fps)

        return f"{hours:02d}:{minutes:02d}:{seconds:02d}:{frames:02d}"

    def _path_to_file_url(self, path: Path) -> str:
        """Convert path to file:// URL."""
        return f"file:///{html.escape(str(path.absolute()))}"

    def generate_all(
        self,
        output_dir: Path,
        base_name: Optional[str] = None,
    ) -> dict[str, Path]:
        """
        Generate all timeline formats.

        Args:
            output_dir: Output directory
            base_name: Base filename (defaults to project name)

        Returns:
            Dictionary of format -> path
        """
        output_dir.mkdir(parents=True, exist_ok=True)
        base_name = base_name or self.project_name

        results = {}

        # FCPXML
        fcpxml_path = output_dir / f"{base_name}.fcpxml"
        results["fcpxml"] = self.to_fcpxml(fcpxml_path)

        # EDL
        edl_path = output_dir / f"{base_name}.edl"
        results["edl"] = self.to_edl(edl_path)

        # Premiere XML
        prem_path = output_dir / f"{base_name}_premiere.xml"
        results["premiere_xml"] = self.to_premiere_xml(prem_path)

        return results
